version: '2.0'
services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    networks:
      - backend
    volumes:
      - "/volume/wordpress/.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 'P@ssw0rd'

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: apache-web
    networks:
      - backend
      - frontend
    volumes:
      - "/volume/wordpress/wp_html:/var/www/html"
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: 'P@ssw0rd'

networks:
  backend:
    external: true
  frontend:
    external: true
